config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'home#index'
  get '/betcheck' => 'betcheck#index'
  post '/betcheck/color_targets'

  get '/ajax' => 'ajax#index'
  get '/ajax/upanel' => 'ajax#upanel'
  resources :betconditions do
    member do
      get :try_result
      get :analyze_result
    end
  end

end

app/views/layouts/_meta_tags.html.slim
meta charset='UTF-8'

-# デスクリプションを不用意に変更されないようにする
meta content='NOYDIR' name='ROBOTS'
meta content='NOODP' name='ROBOTS'

-# Twitter用のTwitter Cart対策
meta content='summary' name='twitter:card'
meta content='@twitter_user_name' name='twitter:site'

-# モバイルに対応している場合のみ書く
link media='handheld' rel='alternate' href="#{canonical_url}"

-# RSSを作成している場合のみ書く
-#link#gallery href='RSS-URL' rel='alternate' title='' type='application/rss+xml'

- set_meta_tags site: page_title
- set_meta_tags description: page_description
- set_meta_tags keywords: page_keywords
- set_meta_tags canonical: canonical_url

ruby:
  opg = {
          title: page_title,
          type: 'website',
          url: canonical_url,
          image: page_og_image,
          site_name: Settings.site.title,
          description: page_description,
          locale: 'ja_JP' # 英語版を作る場合は要変更
  }

- set_meta_tags :open_graph => opg
= Settings.reload!
= display_meta_tags
meta content="#{Settings.facebook.app_id}" property='fb:app_id'

app/views/layouts/application.html.slim
doctype html
html lang="ja"
  head
    = render partial: 'layouts/meta_tags'
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    /! For third-generation iPad with high-resolution Retina display:
    /! Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    /! For iPhone with high-resolution Retina display:
    /! Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    /! For first- and second-generation iPad:
    /! Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    /! For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    /! Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    /! For all other devices
    /! Size should be 32 x 32 pixels
    = favicon_link_tag
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /![if lt IE 9]
      | <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script
  body
    .fb-like data-share="true" data-show-faces="true" data-width="450"
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle data-target=".navbar-responsive-collapse" data-toggle="collapse" type="button"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="/"  競馬オッズシミュレーター
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li = link_to "分析", new_betcondition_path(:mode => "analyze")
            li = link_to "シュミレーション", new_betcondition_path(:mode => "try")
            /li = link_to "オッズチェック", betcheck_path
            li = mail_to 'keibasimulator@gmail.com', 'お問い合わせ'
          // ul.nav.navbar-nav.navbar-right
          //   li
          //     p = "ようこそ#{header_user_name}さん"
          //   li.dropdown
          //     a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
          //       span.caret
          //     ul.dropdown-menu
          //       li
          //         a href="#"  ユーザー設定
          //       li
          //         a href="#"  条件一覧
          //       li
          //         a href="#"  Something else here
          //       li.divider role="separator"
          //       li
          //         =link_to "ログアウト", destroy_user_session_path, :method => :delete

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
        // .col-lg-3
          // .well.sidebar-nav
          //   h3 Sidebar
          //   ul.nav.nav-list
          //     li.nav-header Sidebar
          //     li= link_to "Link1", "/try_home"
          //     li= link_to "Link2", "/bet_check"
          //     li= link_to "Link3", "/path3"
          /! /.well
        /! /span
      /! /row
    /! /container
    javascript:
      window.fbAsyncInit = function () {
        FB.init({
          appId: '1856590374568329',
          xfbml: true,
          version: 'v2.6'
        });
      };

      (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {
          return;
        }
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
  = analytics_init if Rails.env.production?

app/views/layouts/error.html.slim
doctype html
html lang="en"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    title= content_for?(:title) ? yield(:title) : "競馬オッズシミュレーター"
    = favicon_link_tag
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    /! For third-generation iPad with high-resolution Retina display:
    /! Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    /! For iPhone with high-resolution Retina display:
    /! Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    /! For first- and second-generation iPad:
    /! Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    /! For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    /! Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    /! For all other devices
    /! Size should be 32 x 32 pixels
    = favicon_link_tag
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /![if lt IE 9]
      | <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script
  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle data-target=".navbar-responsive-collapse" data-toggle="collapse" type="button"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="/"  競馬オッズシミュレーター
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li = link_to "分析", new_betcondition_path(:mode => "analyze")
            li = link_to "検証", new_betcondition_path(:mode => "try")
            li = link_to "オッズチェック", betcheck_path
            li = mail_to 'keibasimulator@gmail.com', 'お問い合わせ'
          // ul.nav.navbar-nav.navbar-right
          //   li
          //     p = "ようこそ#{header_user_name}さん"
          //   li.dropdown
          //     a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
          //       span.caret
          //     ul.dropdown-menu
          //       li
          //         a href="#"  ユーザー設定
          //       li
          //         a href="#"  条件一覧
          //       li
          //         a href="#"  Something else here
          //       li.divider role="separator"
          //       li
          //         =link_to "ログアウト", destroy_user_session_path, :method => :delete

    .container
      .row
        .col-lg-12
          = yield
        // .col-lg-3
          // .well.sidebar-nav
          //   h3 Sidebar
          //   ul.nav.nav-list
          //     li.nav-header Sidebar
          //     li= link_to "Link1", "/try_home"
          //     li= link_to "Link2", "/bet_check"
          //     li= link_to "Link3", "/path3"
          /! /.well
        /! /span
      /! /row
    /! /container